# Add 'root' label to any root file changes
# Quotation marks are required for the leading asterisk
root:
- changed-files:
  - any-glob-to-any-file: '*'

docs:
- changed-files:
  - any-glob-to-any-file:
    - 'docs/**'
    - '**/*.md'
    - 'LICENSE'
    - 'PROJECT'

ci/cd:
- changed-files:
  - any-glob-to-any-file:
    - '.github/**/*'
    - '/*.yaml'

scripts:
- changed-files:
  - any-glob-to-any-file:
    - 'Makefile'
    - 'Dockerfile'
    - 'scripts/**'
    - 'hack/**'

source:
- changed-files:
  - any-glob-to-any-file:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  - all-globs-to-all-files: '!docs/*'

v1:
- base-branch: ['^v1']

v2:
- base-branch: ['^(?!v1)']

feature:
- head-branch: ['^feat', 'feat']

