version: "2"
run:
  # disallows implicit automatic updating of go.mod and fails when any changes to go.mod are needed
  modules-download-mode: readonly

linters:
  enable:
    - asciicheck
    - bidichk
    - durationcheck
    - errname
    - errorlint
    - exportloopref
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nilerr
    - unconvert
    - unused
    - errcheck
    - nolintlint
    - staticcheck
    - goimports

formatters:
  enable:
    - gofmt
