component-definition: ./internal/testdata/kyverno/component-definition.json
plugins:
  kyverno:
    policy-dir: ./internal/testdata/kyverno/policy-resources
    policy-results-dir: ./internal/testdata/kyverno/policy-reports
    temp-dir: /tmp/kyverno
    output-dir: /tmp/kyverno-policies